# AlertManager Configuration
# Manages alerts from Prometheus and routes them to notification channels

global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@company.com'
  smtp_auth_username: 'alertmanager@company.com'
  smtp_auth_password: 'password'

templates:
  - '/etc/alertmanager/templates/*.tmpl'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
  
  routes:
    # Critical alerts go to multiple channels
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      repeat_interval: 30m
      
    # Warning alerts
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 30s
      repeat_interval: 2h
      
    # Infrastructure alerts
    - match:
        alertname: 'InstanceDown'
      receiver: 'infrastructure-alerts'
      
    # Application alerts
    - match:
        service: 'web-app'
      receiver: 'application-alerts'

inhibit_rules:
  # Inhibit warning if critical is firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']

receivers:
  - name: 'default-receiver'
    email_configs:
      - to: 'devops@company.com'
        subject: 'Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Details:
          {{ range .Labels.SortedPairs }} - {{ .Name }} = {{ .Value }}
          {{ end }}
          {{ end }}

  - name: 'critical-alerts'
    email_configs:
      - to: 'devops@company.com,oncall@company.com'
        subject: 'CRITICAL: {{ .GroupLabels.alertname }}'
        body: |
          CRITICAL ALERT!
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.service }}
          Instance: {{ .Labels.instance }}
          
          Runbook: {{ .Annotations.runbook_url }}
          {{ end }}
    
    webhook_configs:
      - url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        send_resolved: true
        title: 'CRITICAL Alert'
        text: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Status: {{ .Status }}
          {{ end }}
    
    webhook_configs:
      - url: 'https://outlook.office.com/webhook/YOUR-TEAMS-WEBHOOK'
        send_resolved: true

  - name: 'warning-alerts'
    email_configs:
      - to: 'devops@company.com'
        subject: 'Warning: {{ .GroupLabels.alertname }}'
        
    webhook_configs:
      - url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        send_resolved: true

  - name: 'infrastructure-alerts'
    email_configs:
      - to: 'infrastructure@company.com'
        subject: 'Infrastructure Alert: {{ .GroupLabels.alertname }}'
        
  - name: 'application-alerts'
    email_configs:
      - to: 'developers@company.com'
        subject: 'Application Alert: {{ .GroupLabels.alertname }}'

# Silence configuration (optional)
# silences:
#   - matchers:
#       - alertname="InfoInhibitor"
#     starts_at: "2024-01-01T00:00:00Z"
#     ends_at: "2024-12-31T23:59:59Z"
#     created_by: "admin"
#     comment: "Silence info alerts"
